export const GET_REPOS = 'GET_REPOS';
export const GET_REPOS_FULFILLED = `${GET_REPOS}_FULFILLED`;
export const GET_REPOS_REJECTED = `${GET_REPOS}_REJECTED`;
export const GET_REPOS_PENDING = `${GET_REPOS}_PENDING`;
export const GET_REPOS_RESET = `${GET_REPOS}_RESET`;

export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_FULFILLED = `${GET_ISSUES}_FULFILLED`;
export const GET_ISSUES_REJECTED = `${GET_ISSUES}_REJECTED`;
export const GET_ISSUES_PENDING = `${GET_ISSUES}_PENDING`;
export const GET_ISSUES_RESET = `${GET_ISSUES}_RESET`;

// Errors
export const ERROR_HTTP = 'ERROR_HTTP';
export const ERROR_HTTP_UNAUTHORIZED = 'ERROR_HTTP_UNAUTHORIZED';
export const ERROR_HTTP_FORBIDDEN = 'ERROR_HTTP_FORBIDDEN';
export const ERROR_HTTP_INTERNAL_SERVER_ERROR = 'ERROR_HTTP_INTERNAL_SERVER_ERROR';
export const ERROR_HTTP_NETWORK = 'ERROR_HTTP_NETWORK';
export const ERROR_HTTP_TIMEOUT = 'ERROR_HTTP_TIMEOUT';
